#!/bin/bash

FILEDIR=/tmp
OPTION=()

values=$(zenity \
	--window-icon=/usr/share/pixmaps/wshot.png \
	--title=Wshot \
	--text="Options" \
	--forms \
	--add-combo="Mode" \
		--combo-values="Full screen|Selected area|Selected window" \
	--add-combo="Include cursor" \
		--combo-values="no|yes" \
	--add-combo="Delay" \
		--combo-values="0|2|4|6|8|10|15|20" \
	--add-combo="Destination" \
		--combo-values="Save file|Clipboard" \
	--add-entry="Custom filename:" \
	--add-combo="File type" \
		--combo-values="png|jpeg" \
	--add-combo="Open saved result?" \
		--combo-values="no|yes" \
)

result=$?

mode=$(echo $values | cut -d '|' -f 1)
cursor=$(echo $values | cut -d '|' -f 2)
wait=$(echo $values | cut -d '|' -f 3)
destination=$(echo $values | cut -d '|' -f 4)
filename=$(echo $values | cut -d '|' -f 5)
filetype=$(echo $values | cut -d '|' -f 6)
open=$(echo $values | cut -d '|' -f 7)


if [ "$result" -eq 1 ];then      # selected cancel
	echo "Goodbye!"
	exit
fi

if [ ! -z "$cursor" ] &&  [ "$cursor" == yes ];then
	OPTION+="-c"
fi

if [ ! -z "$wait" ];then
	sleep $wait
fi

if [ "$mode" == "Full screen" ];then
	true
elif [ "$mode" == "Selected window" ];then
	if pgrep -x sway > /dev/null; then
	GEO="$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)"
	elif pgrep -x wayfire > /dev/null; then
	GEO=$(wf-info |grep Geometry |cut -c 10-)
	else
	zenity \
		--title=Wshot \
		--width=1500 \
		--warning \
		--timeout 3 \
		--text="Compositor does not support automatic window detection."
	GEO="$(slurp)"
	fi
elif [ "$mode" == "Selected area" ];then
	GEO="$(slurp)"
fi

if [ -z "$filename" ];then
	filename=screenshot_$(date +%F_%H.%M.%S)
fi

if [ -z "$destination" ] || [ "$destination" == Clipboard ];then
	if [ -z "$GEO" ]; then
		grim $OPTION -t $filetype - | wl-copy;
	else
		grim $OPTION -t $filetype -g "$GEO" - | wl-copy;
	fi
	notify-send -t 3000 -a Wshot -i /usr/share/pixmaps/wshot.png  "Screenshot copied to clipboard"
else
	if [ -z "$GEO" ]; then
		grim $OPTION -t $filetype $FILEDIR/$filename.$filetype
	else
		grim $OPTION -t $filetype -g "$GEO" $FILEDIR/$filename.$filetype
	fi
	if [ "$open" == yes ]; then
	xdg-open $FILEDIR/$filename.$filetype
	else
		notify-send -t 3000 -a Wshot -i /usr/share/pixmaps/wshot.png  "Screenshot saved as $FILEDIR/$filename.$filetype"
	fi
fi
