#!/bin/bash

FILEDIR=/tmp
OPTION=()


values=$(zenity \
  --title=Wshot \
  --text="Options" \
  --forms \
  --add-combo="Mode" \
    --combo-values="Full screen|Selected area" \
  --add-combo="Include cursor" \
    --combo-values="no|yes" \
    --add-combo="Delay" \
    --combo-values="0|2|4|6|8|10" \
    --add-combo="Destination" \
    --combo-values="Save file|Clipboard" \
      )

result=$?

mode=$(echo $values | cut -d '|' -f 1)
cursor=$(echo $values | cut -d '|' -f 2)
wait=$(echo $values | cut -d '|' -f 3)
destination=$(echo $values | cut -d '|' -f 4)

if [ "$result" -eq 1 ];then      # select cancel
	echo "cancelled"
	exit
fi

if [ ! -z "$cursor" ] &&  [ "$cursor" == yes ];then
	OPTION+="-c"
fi

if [ -z "$mode" ] ;then       # select nothing
	echo "mode is null"
	zenity \
		--title=Wshot \
		--width=200 \
		--warning \
		--text="Mode empty"
	exit
fi

if [ ! -z "$wait" ];then
	sleep $wait
fi

if [ "$mode" == "Full screen" ];then  # select full screen
	true
#elif [ "$mode" == "Specific window" ];then  # select specify window under sway
#	GEO="$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)"
elif [ "$mode" == "Selected area" ];then  # select area
	GEO="$(slurp)"
else                         # error
	echo $mode
fi

if [ -z "$destination" ] || [ "$destination" == Clipboard ];then
	if [ -z "$GEO" ]; then
		grim $OPTION - | wl-copy;
		notify-send -t 2000 -a Wshot -i accessories-screenshot "Full screenshot copied to clipboard"
	else
		grim $OPTION -g "$GEO" - | wl-copy;
		notify-send -t 2000 -a Wshot -i accessories-screenshot "Area screenshot copied to clipboard"
	fi
else
	if [ -z "$GEO" ]; then
		grim $OPTION $FILEDIR/screenshot_full_$(date +%F_%H.%M.%S).png
		notify-send -t 2000 -a Wshot -i accessories-screenshot "Full Screenshot saved"
	else
		grim $OPTION -g "$GEO" $FILEDIR/screenshot_area_$(date +%F_%H.%M.%S).png
		notify-send -t 2000 -a Wshot -i accessories-screenshot "Area screenshot saved"
	fi
fi
