#!/bin/bash

FILEDIR=/tmp
OPTION=()

values=$(qarma \
	--title=Wshot \
	--text="Options" \
	--forms \
	--add-combo="Mode" \
		--combo-values="Full screen|Selected window|Selected area" \
	--add-combo="Include cursor" \
		--combo-values="no|yes" \
	--add-combo="Delay" \
		--combo-values="0|2|4|6|8|10|15|20" \
	--add-combo="Destination" \
		--combo-values="Save file|Clipboard" \
	--add-entry="Custom filename:" \
	--add-combo="Open saved result?" \
		--combo-values="no|yes" \
)

result=$?

mode=$(echo $values | cut -d '|' -f 1)
cursor=$(echo $values | cut -d '|' -f 2)
wait=$(echo $values | cut -d '|' -f 3)
destination=$(echo $values | cut -d '|' -f 4)
filename=$(echo $values | cut -d '|' -f 5)
open=$(echo $values | cut -d '|' -f 6)

if [ "$result" -eq 1 ];then      # select cancel
	echo "Quitting..."
	exit
fi

if [ ! -z "$cursor" ] &&  [ "$cursor" == yes ];then
	OPTION+="-c"
fi

if [ ! -z "$wait" ];then
	sleep $wait
fi

if [ "$mode" == "Full screen" ];then
	true
elif [ "$mode" == "Selected window" ];then
	if pgrep -x sway > /dev/null; then
	GEO="$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)"
	elif pgrep -x wayfire > /dev/null; then
	GEO=$(wf-info |grep Geometry |cut -c 10-)
	else
	qarma \
		--title=Wshot \
		--width=1500 \
		--warning \
		--text="Compositor in use does not support window detection."
	exit
	fi
elif [ "$mode" == "Selected area" ];then
	GEO="$(slurp)"
fi

if [ -z "$filename" ];then
	filename=screenshot_$(date +%F_%H.%M.%S)
fi

if [ -z "$destination" ] || [ "$destination" == Clipboard ];then
	if [ -z "$GEO" ]; then
		grim $OPTION - | wl-copy;
	else
		grim $OPTION -g "$GEO" - | wl-copy;
	fi
	notify-send -t 2000 -a Wshot -i accessories-screenshot "Screenshot copied to clipboard"
else
	if [ -z "$GEO" ]; then
		grim $OPTION $FILEDIR/$filename.png
	else
		grim $OPTION -g "$GEO" $FILEDIR/$filename.png
	fi
	if [ "$open" == yes ]; then
	xdg-open $FILEDIR/$filename.png
	else
		notify-send -t 2000 -a Wshot -i accessories-screenshot "Screenshot saved in $FILEDIR"
	fi
fi
